closeType:
  parent_url: "https://ec.sinopec.com/f/supp/bid/queryInquiryotices.do?"
  typeId: "150"

openType:
  parent_url: "https://ec.sinopec.com/f/supp/bid/queryBidNotices.do?"
  typeId: "50"

listing_url: 'https://ec.sinopec.com/f/supp/notice/bidNotice.do?id='
store_page_string: "webpage/{}.html"
db_name: "test.db"
pageNo: 50